#!/bin/bash

origin="$2"

# True Days
case $( uname -s ) in
    Darwin) true_days=$(( ($(gdate --date="00:00 UTC" +%s) - $(gdate --date="$origin UTC" +%s) ) / 86400 + 1 ));;
    *)      true_days=$(( ($(date --date="00:00 UTC" +%s) - $(date --date="$origin UTC" +%s) ) / 86400 + 1 ));;
esac

# Date as a decimal
decimal_date=$(awk "BEGIN{printf \"%.4f\n\", $true_days/400}")

# Year
y=${decimal_date:0:2}

# Month
m=$(( ${decimal_date:3:1} + 1 ))

# Day
if [[ ${decimal_date:4:1} = \0 ]] ; then
  d=$(( $(( ${decimal_date:5:7} / 25 )) + 1))
else
  d=$(( $(( ${decimal_date:4:7} / 25 )) + 1 ))
fi
y=$(( ($true_days) / 400 ))

# Commands & Output
case "$1" in
    -td) echo "$true_days";;
    -dd) echo "$y-$m-$d $decimal_date";;
    -sd) echo "$y-$m-$d";;
    *  ) echo "Please select mode: -td (true days), -dd (decimal days), -sd (standard days)";;
esac